spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://host.docker.internal:25432/bonds}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ru.misterparser.bonds: DEBUG
    root: INFO